### ISSUE TITLE
PLEASE UPDATE GAMESIR APPS FOR ANDROID 12

### ISSUE THREAD

**Issue by Dhonystark007** [gamesir123/app#96]
Dear @gamesir123 please update your gamesir application because there's some bug that prevent us open the apps in Android 12 phones. 
Heres the error code that i copied from my phone. 
![Screenshot_2022-08-12-22-10-58-117_com miui home](https://user-images.githubusercontent.com/111137432/184385559-c8b86140-5d47-4c15-b1f6-c6769bcb0f6f.jpg)

{{
java.lang.VerifyError: Rejecting class com.xiaoji.gameworld.activity.MyApplication that attempts to sub-type erroneous class com.xiaoji.virtualtouchutil.application.VtouchApplication (declaration of 'com.xiaoji.gameworld.activity.MyApplication' appears in /data/user/0/com.xiaoji.xtouch/Anonymous-DexFile@2477972778.jar)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at s.h.e.l.l.A.instantiateApplication(Unknown Source:14)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1177)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1377)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7026)
	at android.app.ActivityThread.access$1700(ActivityThread.java:273)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2157)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8256)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.VerifyError: Rejecting class com.xiaoji.virtualtouchutil.application.VtouchApplication that attempts to sub-type erroneous class com.xiaoji.gwlibrary.BaseApplication (declaration of 'com.xiaoji.virtualtouchutil.application.VtouchApplication' appears in /data/user/0/com.xiaoji.xtouch/Anonymous-DexFile@2477972778.jar)
	... 15 more
Caused by: java.lang.VerifyError: Verifier rejected class com.xiaoji.gwlibrary.BaseApplication: void com.xiaoji.gwlibrary.BaseApplication.<init>() failed to verify: void com.xiaoji.gwlibrary.BaseApplication.<init>(): [0xF] Constructor returning without calling superclass constructor (declaration of 'com.xiaoji.gwlibrary.BaseApplication' appears in /data/user/0/com.xiaoji.xtouch/Anonymous-DexFile@2477972778.jar)
}}

**Comment by Sn0rlaxxxx** [comment]
I have the same issue

**Comment by mrkzz88** [comment]
The same to

**Comment by SteveAllen1985** [comment]
Mine won't load but gives a clear out message

**Comment by keensshi** [comment]
I have the same when turning on the application automatically throws

**Comment by keensshi** [comment]
I have the same thing when turning on the app it automatically sheds

**Comment by keensshi** [comment]
I have the same thing when turning on the app it automatically sheds

**Comment by keensshi** [comment]
I have the same thing when turning on the app it automatically sheds

**Comment by keensshi** [comment]
Proszę naprawcie to Android 12

**Comment by keensshi** [comment]
please fix this problem

**Comment by carbine1201** [comment]
Waiting for the fix..all versions doesn't seem to work..
